name: Template-Plugin-RoundRobin
version: 0.01
abstract: Server data in a round robin manner.
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Template: 0
  Data::RoundRobin: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
